# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona_client
from persona_client.models.inline_response4032_email_not_authorized import InlineResponse4032EmailNotAuthorized  # noqa: E501
from persona_client.rest import ApiException


class TestInlineResponse4032EmailNotAuthorized(unittest.TestCase):
    """InlineResponse4032EmailNotAuthorized unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4032EmailNotAuthorized(self):
        """Test InlineResponse4032EmailNotAuthorized"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona_client.models.inline_response4032_email_not_authorized.InlineResponse4032EmailNotAuthorized()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
