# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.code_for_token_data import CodeForTokenData  # noqa: E501
from persona.rest import ApiException


class TestCodeForTokenData(unittest.TestCase):
    """CodeForTokenData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodeForTokenData(self):
        """Test CodeForTokenData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.code_for_token_data.CodeForTokenData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
