# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.user_update_address import UserUpdateAddress  # noqa: E501
from persona.rest import ApiException


class TestUserUpdateAddress(unittest.TestCase):
    """UserUpdateAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserUpdateAddress(self):
        """Test UserUpdateAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.user_update_address.UserUpdateAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
