# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_response500 import InlineResponse500  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineResponse500(unittest.TestCase):
    """InlineResponse500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse500(self):
        """Test InlineResponse500"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_response500.InlineResponse500()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
