# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.login_data import LoginData  # noqa: E501
from persona.rest import ApiException


class TestLoginData(unittest.TestCase):
    """LoginData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginData(self):
        """Test LoginData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.login_data.LoginData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
