# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.package import Package  # noqa: E501
from openapi_client.rest import ApiException


class TestPackage(unittest.TestCase):
    """Package unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackage(self):
        """Test Package"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.package.Package()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
