# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.inline_response403_invalid_credentials import InlineResponse403InvalidCredentials  # noqa: E501
from persona.rest import ApiException


class TestInlineResponse403InvalidCredentials(unittest.TestCase):
    """InlineResponse403InvalidCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse403InvalidCredentials(self):
        """Test InlineResponse403InvalidCredentials"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.inline_response403_invalid_credentials.InlineResponse403InvalidCredentials()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
