# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.login_data_sso import LoginDataSSO  # noqa: E501
from openapi_client.rest import ApiException


class TestLoginDataSSO(unittest.TestCase):
    """LoginDataSSO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginDataSSO(self):
        """Test LoginDataSSO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.login_data_sso.LoginDataSSO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
