# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.package_campaign import PackageCampaign  # noqa: E501
from persona.rest import ApiException


class TestPackageCampaign(unittest.TestCase):
    """PackageCampaign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageCampaign(self):
        """Test PackageCampaign"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.package_campaign.PackageCampaign()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
