# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona_client
from persona_client.models.inline_response400_invalid_request_body import InlineResponse400InvalidRequestBody  # noqa: E501
from persona_client.rest import ApiException


class TestInlineResponse400InvalidRequestBody(unittest.TestCase):
    """InlineResponse400InvalidRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse400InvalidRequestBody(self):
        """Test InlineResponse400InvalidRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona_client.models.inline_response400_invalid_request_body.InlineResponse400InvalidRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
