# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.api.account_api import AccountApi  # noqa: E501
from persona.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = persona.api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_password_check_token_post(self):
        """Test case for account_password_check_token_post

        Validate password reset token  # noqa: E501
        """
        pass

    def test_account_password_forgot_post(self):
        """Test case for account_password_forgot_post

        Request password reset link  # noqa: E501
        """
        pass

    def test_account_password_reset_post(self):
        """Test case for account_password_reset_post

        Reset a forgotten password with a token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
