# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.inline_response4032_email_address_in_use import InlineResponse4032EmailAddressInUse  # noqa: E501
from persona.rest import ApiException


class TestInlineResponse4032EmailAddressInUse(unittest.TestCase):
    """InlineResponse4032EmailAddressInUse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4032EmailAddressInUse(self):
        """Test InlineResponse4032EmailAddressInUse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.inline_response4032_email_address_in_use.InlineResponse4032EmailAddressInUse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
