# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.campaign import Campaign  # noqa: E501
from openapi_client.rest import ApiException


class TestCampaign(unittest.TestCase):
    """Campaign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCampaign(self):
        """Test Campaign"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.campaign.Campaign()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
