# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.inline_response403 import InlineResponse403  # noqa: E501
from persona.rest import ApiException


class TestInlineResponse403(unittest.TestCase):
    """InlineResponse403 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse403(self):
        """Test InlineResponse403"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.inline_response403.InlineResponse403()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
