# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.user_update import UserUpdate  # noqa: E501
from persona.rest import ApiException


class TestUserUpdate(unittest.TestCase):
    """UserUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserUpdate(self):
        """Test UserUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.user_update.UserUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
