# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_response4031_access_token_expired import InlineResponse4031AccessTokenExpired  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineResponse4031AccessTokenExpired(unittest.TestCase):
    """InlineResponse4031AccessTokenExpired unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4031AccessTokenExpired(self):
        """Test InlineResponse4031AccessTokenExpired"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_response4031_access_token_expired.InlineResponse4031AccessTokenExpired()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
