# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.inline_response4032 import InlineResponse4032  # noqa: E501
from persona.rest import ApiException


class TestInlineResponse4032(unittest.TestCase):
    """InlineResponse4032 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4032(self):
        """Test InlineResponse4032"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.inline_response4032.InlineResponse4032()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
