# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.package_offer import PackageOffer  # noqa: E501
from openapi_client.rest import ApiException


class TestPackageOffer(unittest.TestCase):
    """PackageOffer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageOffer(self):
        """Test PackageOffer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.package_offer.PackageOffer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
