# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.login_response import LoginResponse  # noqa: E501
from persona.rest import ApiException


class TestLoginResponse(unittest.TestCase):
    """LoginResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginResponse(self):
        """Test LoginResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.login_response.LoginResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
