# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.paper import Paper  # noqa: E501
from persona.rest import ApiException


class TestPaper(unittest.TestCase):
    """Paper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaper(self):
        """Test Paper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.paper.Paper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
