# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import persona
from persona.models.package_description import PackageDescription  # noqa: E501
from persona.rest import ApiException


class TestPackageDescription(unittest.TestCase):
    """PackageDescription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPackageDescription(self):
        """Test PackageDescription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = persona.models.package_description.PackageDescription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
