# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_response4032_oauth_failed import InlineResponse4032OauthFailed  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineResponse4032OauthFailed(unittest.TestCase):
    """InlineResponse4032OauthFailed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4032OauthFailed(self):
        """Test InlineResponse4032OauthFailed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_response4032_oauth_failed.InlineResponse4032OauthFailed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
