# coding: utf-8

# flake8: noqa

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.login_api import LoginApi
from openapi_client.api.users_api import UsersApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
# import models into sdk package
from openapi_client.models.active_days import ActiveDays
from openapi_client.models.address import Address
from openapi_client.models.campaign import Campaign
from openapi_client.models.description_frequency import DescriptionFrequency
from openapi_client.models.inline_response400 import InlineResponse400
from openapi_client.models.inline_response400_invalid_request_body import InlineResponse400InvalidRequestBody
from openapi_client.models.inline_response403 import InlineResponse403
from openapi_client.models.inline_response4031 import InlineResponse4031
from openapi_client.models.inline_response4031_access_token_expired import InlineResponse4031AccessTokenExpired
from openapi_client.models.inline_response4032 import InlineResponse4032
from openapi_client.models.inline_response4032_email_address_in_use import InlineResponse4032EmailAddressInUse
from openapi_client.models.inline_response4032_email_not_authorized import InlineResponse4032EmailNotAuthorized
from openapi_client.models.inline_response4032_oauth_failed import InlineResponse4032OauthFailed
from openapi_client.models.inline_response403_invalid_credentials import InlineResponse403InvalidCredentials
from openapi_client.models.inline_response415 import InlineResponse415
from openapi_client.models.inline_response415_unsupported_media_type import InlineResponse415UnsupportedMediaType
from openapi_client.models.inline_response500 import InlineResponse500
from openapi_client.models.inline_response500_internal_server_error import InlineResponse500InternalServerError
from openapi_client.models.login_data import LoginData
from openapi_client.models.login_data_sso import LoginDataSSO
from openapi_client.models.login_data_so_me import LoginDataSoMe
from openapi_client.models.login_response import LoginResponse
from openapi_client.models.package import Package
from openapi_client.models.package_description import PackageDescription
from openapi_client.models.package_offer import PackageOffer
from openapi_client.models.paper import Paper
from openapi_client.models.product import Product
from openapi_client.models.subscription import Subscription
from openapi_client.models.subscription_dates import SubscriptionDates
from openapi_client.models.user import User
