# coding: utf-8

# flake8: noqa

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.login_api import LoginApi
from openapi_client.api.users_api import UsersApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
# import models into sdk package
from openapi_client.models.active_days import ActiveDays
from openapi_client.models.address import Address
from openapi_client.models.campaign import Campaign
from openapi_client.models.description_frequency import DescriptionFrequency
from openapi_client.models.login_data import LoginData
from openapi_client.models.login_data_sso import LoginDataSSO
from openapi_client.models.login_data_so_me import LoginDataSoMe
from openapi_client.models.login_response import LoginResponse
from openapi_client.models.package import Package
from openapi_client.models.package_description import PackageDescription
from openapi_client.models.package_offer import PackageOffer
from openapi_client.models.paper import Paper
from openapi_client.models.product import Product
from openapi_client.models.subscription import Subscription
from openapi_client.models.subscription_dates import SubscriptionDates
from openapi_client.models.user import User
