# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ActiveDays(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'mon': 'bool',
        'tue': 'bool',
        'wed': 'bool',
        'thu': 'bool',
        'fri': 'bool',
        'sat': 'bool',
        'sun': 'bool'
    }

    attribute_map = {
        'mon': 'mon',
        'tue': 'tue',
        'wed': 'wed',
        'thu': 'thu',
        'fri': 'fri',
        'sat': 'sat',
        'sun': 'sun'
    }

    def __init__(self, mon=None, tue=None, wed=None, thu=None, fri=None, sat=None, sun=None):  # noqa: E501
        """ActiveDays - a model defined in OpenAPI"""  # noqa: E501

        self._mon = None
        self._tue = None
        self._wed = None
        self._thu = None
        self._fri = None
        self._sat = None
        self._sun = None
        self.discriminator = None

        self.mon = mon
        self.tue = tue
        self.wed = wed
        self.thu = thu
        self.fri = fri
        self.sat = sat
        self.sun = sun

    @property
    def mon(self):
        """Gets the mon of this ActiveDays.  # noqa: E501


        :return: The mon of this ActiveDays.  # noqa: E501
        :rtype: bool
        """
        return self._mon

    @mon.setter
    def mon(self, mon):
        """Sets the mon of this ActiveDays.


        :param mon: The mon of this ActiveDays.  # noqa: E501
        :type: bool
        """
        if mon is None:
            raise ValueError("Invalid value for `mon`, must not be `None`")  # noqa: E501

        self._mon = mon

    @property
    def tue(self):
        """Gets the tue of this ActiveDays.  # noqa: E501


        :return: The tue of this ActiveDays.  # noqa: E501
        :rtype: bool
        """
        return self._tue

    @tue.setter
    def tue(self, tue):
        """Sets the tue of this ActiveDays.


        :param tue: The tue of this ActiveDays.  # noqa: E501
        :type: bool
        """
        if tue is None:
            raise ValueError("Invalid value for `tue`, must not be `None`")  # noqa: E501

        self._tue = tue

    @property
    def wed(self):
        """Gets the wed of this ActiveDays.  # noqa: E501


        :return: The wed of this ActiveDays.  # noqa: E501
        :rtype: bool
        """
        return self._wed

    @wed.setter
    def wed(self, wed):
        """Sets the wed of this ActiveDays.


        :param wed: The wed of this ActiveDays.  # noqa: E501
        :type: bool
        """
        if wed is None:
            raise ValueError("Invalid value for `wed`, must not be `None`")  # noqa: E501

        self._wed = wed

    @property
    def thu(self):
        """Gets the thu of this ActiveDays.  # noqa: E501


        :return: The thu of this ActiveDays.  # noqa: E501
        :rtype: bool
        """
        return self._thu

    @thu.setter
    def thu(self, thu):
        """Sets the thu of this ActiveDays.


        :param thu: The thu of this ActiveDays.  # noqa: E501
        :type: bool
        """
        if thu is None:
            raise ValueError("Invalid value for `thu`, must not be `None`")  # noqa: E501

        self._thu = thu

    @property
    def fri(self):
        """Gets the fri of this ActiveDays.  # noqa: E501


        :return: The fri of this ActiveDays.  # noqa: E501
        :rtype: bool
        """
        return self._fri

    @fri.setter
    def fri(self, fri):
        """Sets the fri of this ActiveDays.


        :param fri: The fri of this ActiveDays.  # noqa: E501
        :type: bool
        """
        if fri is None:
            raise ValueError("Invalid value for `fri`, must not be `None`")  # noqa: E501

        self._fri = fri

    @property
    def sat(self):
        """Gets the sat of this ActiveDays.  # noqa: E501


        :return: The sat of this ActiveDays.  # noqa: E501
        :rtype: bool
        """
        return self._sat

    @sat.setter
    def sat(self, sat):
        """Sets the sat of this ActiveDays.


        :param sat: The sat of this ActiveDays.  # noqa: E501
        :type: bool
        """
        if sat is None:
            raise ValueError("Invalid value for `sat`, must not be `None`")  # noqa: E501

        self._sat = sat

    @property
    def sun(self):
        """Gets the sun of this ActiveDays.  # noqa: E501


        :return: The sun of this ActiveDays.  # noqa: E501
        :rtype: bool
        """
        return self._sun

    @sun.setter
    def sun(self, sun):
        """Sets the sun of this ActiveDays.


        :param sun: The sun of this ActiveDays.  # noqa: E501
        :type: bool
        """
        if sun is None:
            raise ValueError("Invalid value for `sun`, must not be `None`")  # noqa: E501

        self._sun = sun

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActiveDays):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
