# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CancelSubscriptionReason(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'reason': 'str',
        'notes': 'str'
    }

    attribute_map = {
        'reason': 'reason',
        'notes': 'notes'
    }

    def __init__(self, reason=None, notes=None):  # noqa: E501
        """CancelSubscriptionReason - a model defined in OpenAPI"""  # noqa: E501

        self._reason = None
        self._notes = None
        self.discriminator = None

        self.reason = reason
        if notes is not None:
            self.notes = notes

    @property
    def reason(self):
        """Gets the reason of this CancelSubscriptionReason.  # noqa: E501

        Cancel reason code  # noqa: E501

        :return: The reason of this CancelSubscriptionReason.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this CancelSubscriptionReason.

        Cancel reason code  # noqa: E501

        :param reason: The reason of this CancelSubscriptionReason.  # noqa: E501
        :type: str
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501
        allowed_values = ["Price", "Distribution", "Content", "OldAge", "Deceased", "Digital", "Other", "ChangeProduct"]  # noqa: E501
        if reason not in allowed_values:
            raise ValueError(
                "Invalid value for `reason` ({0}), must be one of {1}"  # noqa: E501
                .format(reason, allowed_values)
            )

        self._reason = reason

    @property
    def notes(self):
        """Gets the notes of this CancelSubscriptionReason.  # noqa: E501

        Cancel reason explanation  # noqa: E501

        :return: The notes of this CancelSubscriptionReason.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this CancelSubscriptionReason.

        Cancel reason explanation  # noqa: E501

        :param notes: The notes of this CancelSubscriptionReason.  # noqa: E501
        :type: str
        """

        self._notes = notes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CancelSubscriptionReason):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
