# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class FaroUser(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cusno': 'int',
        'name': 'str',
        'address': 'Address',
        'email': 'str',
        'subscriptions': 'list[Subscription]'
    }

    attribute_map = {
        'cusno': 'cusno',
        'name': 'name',
        'address': 'address',
        'email': 'email',
        'subscriptions': 'subscriptions'
    }

    def __init__(self, cusno=None, name=None, address=None, email=None, subscriptions=None):  # noqa: E501
        """FaroUser - a model defined in OpenAPI"""  # noqa: E501

        self._cusno = None
        self._name = None
        self._address = None
        self._email = None
        self._subscriptions = None
        self.discriminator = None

        self.cusno = cusno
        self.name = name
        if address is not None:
            self.address = address
        if email is not None:
            self.email = email
        if subscriptions is not None:
            self.subscriptions = subscriptions

    @property
    def cusno(self):
        """Gets the cusno of this FaroUser.  # noqa: E501


        :return: The cusno of this FaroUser.  # noqa: E501
        :rtype: int
        """
        return self._cusno

    @cusno.setter
    def cusno(self, cusno):
        """Sets the cusno of this FaroUser.


        :param cusno: The cusno of this FaroUser.  # noqa: E501
        :type: int
        """
        if cusno is None:
            raise ValueError("Invalid value for `cusno`, must not be `None`")  # noqa: E501
        if cusno is not None and cusno > 9223372036854775807:  # noqa: E501
            raise ValueError("Invalid value for `cusno`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if cusno is not None and cusno < -9223372036854775808:  # noqa: E501
            raise ValueError("Invalid value for `cusno`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._cusno = cusno

    @property
    def name(self):
        """Gets the name of this FaroUser.  # noqa: E501


        :return: The name of this FaroUser.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FaroUser.


        :param name: The name of this FaroUser.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def address(self):
        """Gets the address of this FaroUser.  # noqa: E501


        :return: The address of this FaroUser.  # noqa: E501
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this FaroUser.


        :param address: The address of this FaroUser.  # noqa: E501
        :type: Address
        """

        self._address = address

    @property
    def email(self):
        """Gets the email of this FaroUser.  # noqa: E501


        :return: The email of this FaroUser.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this FaroUser.


        :param email: The email of this FaroUser.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def subscriptions(self):
        """Gets the subscriptions of this FaroUser.  # noqa: E501


        :return: The subscriptions of this FaroUser.  # noqa: E501
        :rtype: list[Subscription]
        """
        return self._subscriptions

    @subscriptions.setter
    def subscriptions(self, subscriptions):
        """Sets the subscriptions of this FaroUser.


        :param subscriptions: The subscriptions of this FaroUser.  # noqa: E501
        :type: list[Subscription]
        """

        self._subscriptions = subscriptions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FaroUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
