# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class GlobalEntitlementAccess(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'user_uuid': 'str',
        'start_at': 'str',
        'end_at': 'str'
    }

    attribute_map = {
        'user_uuid': 'userUuid',
        'start_at': 'startAt',
        'end_at': 'endAt'
    }

    def __init__(self, user_uuid=None, start_at=None, end_at=None):  # noqa: E501
        """GlobalEntitlementAccess - a model defined in OpenAPI"""  # noqa: E501

        self._user_uuid = None
        self._start_at = None
        self._end_at = None
        self.discriminator = None

        self.user_uuid = user_uuid
        self.start_at = start_at
        self.end_at = end_at

    @property
    def user_uuid(self):
        """Gets the user_uuid of this GlobalEntitlementAccess.  # noqa: E501


        :return: The user_uuid of this GlobalEntitlementAccess.  # noqa: E501
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid):
        """Sets the user_uuid of this GlobalEntitlementAccess.


        :param user_uuid: The user_uuid of this GlobalEntitlementAccess.  # noqa: E501
        :type: str
        """
        if user_uuid is None:
            raise ValueError("Invalid value for `user_uuid`, must not be `None`")  # noqa: E501

        self._user_uuid = user_uuid

    @property
    def start_at(self):
        """Gets the start_at of this GlobalEntitlementAccess.  # noqa: E501


        :return: The start_at of this GlobalEntitlementAccess.  # noqa: E501
        :rtype: str
        """
        return self._start_at

    @start_at.setter
    def start_at(self, start_at):
        """Sets the start_at of this GlobalEntitlementAccess.


        :param start_at: The start_at of this GlobalEntitlementAccess.  # noqa: E501
        :type: str
        """
        if start_at is None:
            raise ValueError("Invalid value for `start_at`, must not be `None`")  # noqa: E501

        self._start_at = start_at

    @property
    def end_at(self):
        """Gets the end_at of this GlobalEntitlementAccess.  # noqa: E501


        :return: The end_at of this GlobalEntitlementAccess.  # noqa: E501
        :rtype: str
        """
        return self._end_at

    @end_at.setter
    def end_at(self, end_at):
        """Sets the end_at of this GlobalEntitlementAccess.


        :param end_at: The end_at of this GlobalEntitlementAccess.  # noqa: E501
        :type: str
        """
        if end_at is None:
            raise ValueError("Invalid value for `end_at`, must not be `None`")  # noqa: E501

        self._end_at = end_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GlobalEntitlementAccess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
