# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse403(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'http_code': 'int',
        'http_status': 'str',
        'invalid_credentials': 'InlineResponse403InvalidCredentials'
    }

    attribute_map = {
        'http_code': 'http_code',
        'http_status': 'http_status',
        'invalid_credentials': 'invalid_credentials'
    }

    def __init__(self, http_code=None, http_status=None, invalid_credentials=None):  # noqa: E501
        """InlineResponse403 - a model defined in OpenAPI"""  # noqa: E501

        self._http_code = None
        self._http_status = None
        self._invalid_credentials = None
        self.discriminator = None

        if http_code is not None:
            self.http_code = http_code
        if http_status is not None:
            self.http_status = http_status
        if invalid_credentials is not None:
            self.invalid_credentials = invalid_credentials

    @property
    def http_code(self):
        """Gets the http_code of this InlineResponse403.  # noqa: E501


        :return: The http_code of this InlineResponse403.  # noqa: E501
        :rtype: int
        """
        return self._http_code

    @http_code.setter
    def http_code(self, http_code):
        """Sets the http_code of this InlineResponse403.


        :param http_code: The http_code of this InlineResponse403.  # noqa: E501
        :type: int
        """

        self._http_code = http_code

    @property
    def http_status(self):
        """Gets the http_status of this InlineResponse403.  # noqa: E501


        :return: The http_status of this InlineResponse403.  # noqa: E501
        :rtype: str
        """
        return self._http_status

    @http_status.setter
    def http_status(self, http_status):
        """Sets the http_status of this InlineResponse403.


        :param http_status: The http_status of this InlineResponse403.  # noqa: E501
        :type: str
        """
        allowed_values = ["Forbidden"]  # noqa: E501
        if http_status not in allowed_values:
            raise ValueError(
                "Invalid value for `http_status` ({0}), must be one of {1}"  # noqa: E501
                .format(http_status, allowed_values)
            )

        self._http_status = http_status

    @property
    def invalid_credentials(self):
        """Gets the invalid_credentials of this InlineResponse403.  # noqa: E501


        :return: The invalid_credentials of this InlineResponse403.  # noqa: E501
        :rtype: InlineResponse403InvalidCredentials
        """
        return self._invalid_credentials

    @invalid_credentials.setter
    def invalid_credentials(self, invalid_credentials):
        """Sets the invalid_credentials of this InlineResponse403.


        :param invalid_credentials: The invalid_credentials of this InlineResponse403.  # noqa: E501
        :type: InlineResponse403InvalidCredentials
        """

        self._invalid_credentials = invalid_credentials

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse403):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
