# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse4032(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'email_address_in_use': 'InlineResponse4032EmailAddressInUse',
        'http_code': 'int',
        'oauth_failed': 'InlineResponse4032OauthFailed',
        'http_status': 'str',
        'email_not_authorized': 'InlineResponse4032EmailNotAuthorized'
    }

    attribute_map = {
        'email_address_in_use': 'email_address_in_use',
        'http_code': 'http_code',
        'oauth_failed': 'oauth_failed',
        'http_status': 'http_status',
        'email_not_authorized': 'email_not_authorized'
    }

    def __init__(self, email_address_in_use=None, http_code=None, oauth_failed=None, http_status=None, email_not_authorized=None):  # noqa: E501
        """InlineResponse4032 - a model defined in OpenAPI"""  # noqa: E501

        self._email_address_in_use = None
        self._http_code = None
        self._oauth_failed = None
        self._http_status = None
        self._email_not_authorized = None
        self.discriminator = None

        if email_address_in_use is not None:
            self.email_address_in_use = email_address_in_use
        if http_code is not None:
            self.http_code = http_code
        if oauth_failed is not None:
            self.oauth_failed = oauth_failed
        if http_status is not None:
            self.http_status = http_status
        if email_not_authorized is not None:
            self.email_not_authorized = email_not_authorized

    @property
    def email_address_in_use(self):
        """Gets the email_address_in_use of this InlineResponse4032.  # noqa: E501


        :return: The email_address_in_use of this InlineResponse4032.  # noqa: E501
        :rtype: InlineResponse4032EmailAddressInUse
        """
        return self._email_address_in_use

    @email_address_in_use.setter
    def email_address_in_use(self, email_address_in_use):
        """Sets the email_address_in_use of this InlineResponse4032.


        :param email_address_in_use: The email_address_in_use of this InlineResponse4032.  # noqa: E501
        :type: InlineResponse4032EmailAddressInUse
        """

        self._email_address_in_use = email_address_in_use

    @property
    def http_code(self):
        """Gets the http_code of this InlineResponse4032.  # noqa: E501


        :return: The http_code of this InlineResponse4032.  # noqa: E501
        :rtype: int
        """
        return self._http_code

    @http_code.setter
    def http_code(self, http_code):
        """Sets the http_code of this InlineResponse4032.


        :param http_code: The http_code of this InlineResponse4032.  # noqa: E501
        :type: int
        """

        self._http_code = http_code

    @property
    def oauth_failed(self):
        """Gets the oauth_failed of this InlineResponse4032.  # noqa: E501


        :return: The oauth_failed of this InlineResponse4032.  # noqa: E501
        :rtype: InlineResponse4032OauthFailed
        """
        return self._oauth_failed

    @oauth_failed.setter
    def oauth_failed(self, oauth_failed):
        """Sets the oauth_failed of this InlineResponse4032.


        :param oauth_failed: The oauth_failed of this InlineResponse4032.  # noqa: E501
        :type: InlineResponse4032OauthFailed
        """

        self._oauth_failed = oauth_failed

    @property
    def http_status(self):
        """Gets the http_status of this InlineResponse4032.  # noqa: E501


        :return: The http_status of this InlineResponse4032.  # noqa: E501
        :rtype: str
        """
        return self._http_status

    @http_status.setter
    def http_status(self, http_status):
        """Sets the http_status of this InlineResponse4032.


        :param http_status: The http_status of this InlineResponse4032.  # noqa: E501
        :type: str
        """
        allowed_values = ["Forbidden"]  # noqa: E501
        if http_status not in allowed_values:
            raise ValueError(
                "Invalid value for `http_status` ({0}), must be one of {1}"  # noqa: E501
                .format(http_status, allowed_values)
            )

        self._http_status = http_status

    @property
    def email_not_authorized(self):
        """Gets the email_not_authorized of this InlineResponse4032.  # noqa: E501


        :return: The email_not_authorized of this InlineResponse4032.  # noqa: E501
        :rtype: InlineResponse4032EmailNotAuthorized
        """
        return self._email_not_authorized

    @email_not_authorized.setter
    def email_not_authorized(self, email_not_authorized):
        """Sets the email_not_authorized of this InlineResponse4032.


        :param email_not_authorized: The email_not_authorized of this InlineResponse4032.  # noqa: E501
        :type: InlineResponse4032EmailNotAuthorized
        """

        self._email_not_authorized = email_not_authorized

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse4032):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
