# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class LegalConsent(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'screen_name': 'str',
        'consent_id': 'str',
        'date_accepted': 'str'
    }

    attribute_map = {
        'screen_name': 'screenName',
        'consent_id': 'consentId',
        'date_accepted': 'dateAccepted'
    }

    def __init__(self, screen_name=None, consent_id=None, date_accepted=None):  # noqa: E501
        """LegalConsent - a model defined in OpenAPI"""  # noqa: E501

        self._screen_name = None
        self._consent_id = None
        self._date_accepted = None
        self.discriminator = None

        self.screen_name = screen_name
        self.consent_id = consent_id
        self.date_accepted = date_accepted

    @property
    def screen_name(self):
        """Gets the screen_name of this LegalConsent.  # noqa: E501


        :return: The screen_name of this LegalConsent.  # noqa: E501
        :rtype: str
        """
        return self._screen_name

    @screen_name.setter
    def screen_name(self, screen_name):
        """Sets the screen_name of this LegalConsent.


        :param screen_name: The screen_name of this LegalConsent.  # noqa: E501
        :type: str
        """
        if screen_name is None:
            raise ValueError("Invalid value for `screen_name`, must not be `None`")  # noqa: E501

        self._screen_name = screen_name

    @property
    def consent_id(self):
        """Gets the consent_id of this LegalConsent.  # noqa: E501


        :return: The consent_id of this LegalConsent.  # noqa: E501
        :rtype: str
        """
        return self._consent_id

    @consent_id.setter
    def consent_id(self, consent_id):
        """Sets the consent_id of this LegalConsent.


        :param consent_id: The consent_id of this LegalConsent.  # noqa: E501
        :type: str
        """
        if consent_id is None:
            raise ValueError("Invalid value for `consent_id`, must not be `None`")  # noqa: E501

        self._consent_id = consent_id

    @property
    def date_accepted(self):
        """Gets the date_accepted of this LegalConsent.  # noqa: E501


        :return: The date_accepted of this LegalConsent.  # noqa: E501
        :rtype: str
        """
        return self._date_accepted

    @date_accepted.setter
    def date_accepted(self, date_accepted):
        """Sets the date_accepted of this LegalConsent.


        :param date_accepted: The date_accepted of this LegalConsent.  # noqa: E501
        :type: str
        """
        if date_accepted is None:
            raise ValueError("Invalid value for `date_accepted`, must not be `None`")  # noqa: E501

        self._date_accepted = date_accepted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LegalConsent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
