# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class LoginResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'token': 'str',
        'sso_code': 'str',
        'uuid': 'str'
    }

    attribute_map = {
        'token': 'token',
        'sso_code': 'ssoCode',
        'uuid': 'uuid'
    }

    def __init__(self, token=None, sso_code=None, uuid=None):  # noqa: E501
        """LoginResponse - a model defined in OpenAPI"""  # noqa: E501

        self._token = None
        self._sso_code = None
        self._uuid = None
        self.discriminator = None

        self.token = token
        if sso_code is not None:
            self.sso_code = sso_code
        self.uuid = uuid

    @property
    def token(self):
        """Gets the token of this LoginResponse.  # noqa: E501


        :return: The token of this LoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this LoginResponse.


        :param token: The token of this LoginResponse.  # noqa: E501
        :type: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def sso_code(self):
        """Gets the sso_code of this LoginResponse.  # noqa: E501


        :return: The sso_code of this LoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._sso_code

    @sso_code.setter
    def sso_code(self, sso_code):
        """Sets the sso_code of this LoginResponse.


        :param sso_code: The sso_code of this LoginResponse.  # noqa: E501
        :type: str
        """

        self._sso_code = sso_code

    @property
    def uuid(self):
        """Gets the uuid of this LoginResponse.  # noqa: E501


        :return: The uuid of this LoginResponse.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this LoginResponse.


        :param uuid: The uuid of this LoginResponse.  # noqa: E501
        :type: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoginResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
