# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    OpenAPI spec version: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class LoginDataSoMe(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'provider': 'str',
        'some_token': 'str',
        'merge_token': 'str'
    }

    attribute_map = {
        'provider': 'provider',
        'some_token': 'someToken',
        'merge_token': 'mergeToken'
    }

    def __init__(self, provider=None, some_token=None, merge_token=None):  # noqa: E501
        """LoginDataSoMe - a model defined in OpenAPI"""  # noqa: E501

        self._provider = None
        self._some_token = None
        self._merge_token = None
        self.discriminator = None

        self.provider = provider
        self.some_token = some_token
        if merge_token is not None:
            self.merge_token = merge_token

    @property
    def provider(self):
        """Gets the provider of this LoginDataSoMe.  # noqa: E501


        :return: The provider of this LoginDataSoMe.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this LoginDataSoMe.


        :param provider: The provider of this LoginDataSoMe.  # noqa: E501
        :type: str
        """
        if provider is None:
            raise ValueError("Invalid value for `provider`, must not be `None`")  # noqa: E501

        self._provider = provider

    @property
    def some_token(self):
        """Gets the some_token of this LoginDataSoMe.  # noqa: E501


        :return: The some_token of this LoginDataSoMe.  # noqa: E501
        :rtype: str
        """
        return self._some_token

    @some_token.setter
    def some_token(self, some_token):
        """Sets the some_token of this LoginDataSoMe.


        :param some_token: The some_token of this LoginDataSoMe.  # noqa: E501
        :type: str
        """
        if some_token is None:
            raise ValueError("Invalid value for `some_token`, must not be `None`")  # noqa: E501

        self._some_token = some_token

    @property
    def merge_token(self):
        """Gets the merge_token of this LoginDataSoMe.  # noqa: E501


        :return: The merge_token of this LoginDataSoMe.  # noqa: E501
        :rtype: str
        """
        return self._merge_token

    @merge_token.setter
    def merge_token(self, merge_token):
        """Sets the merge_token of this LoginDataSoMe.


        :param merge_token: The merge_token of this LoginDataSoMe.  # noqa: E501
        :type: str
        """

        self._merge_token = merge_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoginDataSoMe):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
