# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PastTemporaryAddress(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'country_code': 'str',
        'zipcode': 'str',
        'city_name': 'str',
        'street': 'str',
        'temporary_name': 'str'
    }

    attribute_map = {
        'country_code': 'countryCode',
        'zipcode': 'zipcode',
        'city_name': 'cityName',
        'street': 'street',
        'temporary_name': 'temporaryName'
    }

    def __init__(self, country_code=None, zipcode=None, city_name=None, street=None, temporary_name=None):  # noqa: E501
        """PastTemporaryAddress - a model defined in OpenAPI"""  # noqa: E501

        self._country_code = None
        self._zipcode = None
        self._city_name = None
        self._street = None
        self._temporary_name = None
        self.discriminator = None

        self.country_code = country_code
        self.zipcode = zipcode
        if city_name is not None:
            self.city_name = city_name
        self.street = street
        if temporary_name is not None:
            self.temporary_name = temporary_name

    @property
    def country_code(self):
        """Gets the country_code of this PastTemporaryAddress.  # noqa: E501


        :return: The country_code of this PastTemporaryAddress.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this PastTemporaryAddress.


        :param country_code: The country_code of this PastTemporaryAddress.  # noqa: E501
        :type: str
        """
        if country_code is None:
            raise ValueError("Invalid value for `country_code`, must not be `None`")  # noqa: E501

        self._country_code = country_code

    @property
    def zipcode(self):
        """Gets the zipcode of this PastTemporaryAddress.  # noqa: E501


        :return: The zipcode of this PastTemporaryAddress.  # noqa: E501
        :rtype: str
        """
        return self._zipcode

    @zipcode.setter
    def zipcode(self, zipcode):
        """Sets the zipcode of this PastTemporaryAddress.


        :param zipcode: The zipcode of this PastTemporaryAddress.  # noqa: E501
        :type: str
        """
        if zipcode is None:
            raise ValueError("Invalid value for `zipcode`, must not be `None`")  # noqa: E501

        self._zipcode = zipcode

    @property
    def city_name(self):
        """Gets the city_name of this PastTemporaryAddress.  # noqa: E501


        :return: The city_name of this PastTemporaryAddress.  # noqa: E501
        :rtype: str
        """
        return self._city_name

    @city_name.setter
    def city_name(self, city_name):
        """Sets the city_name of this PastTemporaryAddress.


        :param city_name: The city_name of this PastTemporaryAddress.  # noqa: E501
        :type: str
        """

        self._city_name = city_name

    @property
    def street(self):
        """Gets the street of this PastTemporaryAddress.  # noqa: E501


        :return: The street of this PastTemporaryAddress.  # noqa: E501
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this PastTemporaryAddress.


        :param street: The street of this PastTemporaryAddress.  # noqa: E501
        :type: str
        """
        if street is None:
            raise ValueError("Invalid value for `street`, must not be `None`")  # noqa: E501

        self._street = street

    @property
    def temporary_name(self):
        """Gets the temporary_name of this PastTemporaryAddress.  # noqa: E501


        :return: The temporary_name of this PastTemporaryAddress.  # noqa: E501
        :rtype: str
        """
        return self._temporary_name

    @temporary_name.setter
    def temporary_name(self, temporary_name):
        """Sets the temporary_name of this PastTemporaryAddress.


        :param temporary_name: The temporary_name of this PastTemporaryAddress.  # noqa: E501
        :type: str
        """

        self._temporary_name = temporary_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PastTemporaryAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
