# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PersistedEntitlementAccess(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'start_at': 'str',
        'end_at': 'str',
        'only_to_products': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'start_at': 'startAt',
        'end_at': 'endAt',
        'only_to_products': 'onlyToProducts'
    }

    def __init__(self, id=None, start_at=None, end_at=None, only_to_products=None):  # noqa: E501
        """PersistedEntitlementAccess - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._start_at = None
        self._end_at = None
        self._only_to_products = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.start_at = start_at
        self.end_at = end_at
        if only_to_products is not None:
            self.only_to_products = only_to_products

    @property
    def id(self):
        """Gets the id of this PersistedEntitlementAccess.  # noqa: E501


        :return: The id of this PersistedEntitlementAccess.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PersistedEntitlementAccess.


        :param id: The id of this PersistedEntitlementAccess.  # noqa: E501
        :type: int
        """
        if id is not None and id > 9223372036854775807:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if id is not None and id < -9223372036854775808:  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._id = id

    @property
    def start_at(self):
        """Gets the start_at of this PersistedEntitlementAccess.  # noqa: E501


        :return: The start_at of this PersistedEntitlementAccess.  # noqa: E501
        :rtype: str
        """
        return self._start_at

    @start_at.setter
    def start_at(self, start_at):
        """Sets the start_at of this PersistedEntitlementAccess.


        :param start_at: The start_at of this PersistedEntitlementAccess.  # noqa: E501
        :type: str
        """
        if start_at is None:
            raise ValueError("Invalid value for `start_at`, must not be `None`")  # noqa: E501

        self._start_at = start_at

    @property
    def end_at(self):
        """Gets the end_at of this PersistedEntitlementAccess.  # noqa: E501


        :return: The end_at of this PersistedEntitlementAccess.  # noqa: E501
        :rtype: str
        """
        return self._end_at

    @end_at.setter
    def end_at(self, end_at):
        """Sets the end_at of this PersistedEntitlementAccess.


        :param end_at: The end_at of this PersistedEntitlementAccess.  # noqa: E501
        :type: str
        """
        if end_at is None:
            raise ValueError("Invalid value for `end_at`, must not be `None`")  # noqa: E501

        self._end_at = end_at

    @property
    def only_to_products(self):
        """Gets the only_to_products of this PersistedEntitlementAccess.  # noqa: E501


        :return: The only_to_products of this PersistedEntitlementAccess.  # noqa: E501
        :rtype: list[str]
        """
        return self._only_to_products

    @only_to_products.setter
    def only_to_products(self, only_to_products):
        """Sets the only_to_products of this PersistedEntitlementAccess.


        :param only_to_products: The only_to_products of this PersistedEntitlementAccess.  # noqa: E501
        :type: list[str]
        """

        self._only_to_products = only_to_products

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PersistedEntitlementAccess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
