# coding: utf-8

"""
    Persona

    KSF Media unified login service  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class UserUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'first_name': 'str',
        'last_name': 'str',
        'address': 'UserUpdateAddress',
        'email': 'str',
        'phone': 'str',
        'pending_address_changes': 'list[object]',
        'update_cusno': 'int'
    }

    attribute_map = {
        'first_name': 'firstName',
        'last_name': 'lastName',
        'address': 'address',
        'email': 'email',
        'phone': 'phone',
        'pending_address_changes': 'pendingAddressChanges',
        'update_cusno': 'updateCusno'
    }

    def __init__(self, first_name=None, last_name=None, address=None, email=None, phone=None, pending_address_changes=None, update_cusno=None):  # noqa: E501
        """UserUpdate - a model defined in OpenAPI"""  # noqa: E501

        self._first_name = None
        self._last_name = None
        self._address = None
        self._email = None
        self._phone = None
        self._pending_address_changes = None
        self._update_cusno = None
        self.discriminator = None

        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if address is not None:
            self.address = address
        if email is not None:
            self.email = email
        if phone is not None:
            self.phone = phone
        if pending_address_changes is not None:
            self.pending_address_changes = pending_address_changes
        if update_cusno is not None:
            self.update_cusno = update_cusno

    @property
    def first_name(self):
        """Gets the first_name of this UserUpdate.  # noqa: E501


        :return: The first_name of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserUpdate.


        :param first_name: The first_name of this UserUpdate.  # noqa: E501
        :type: str
        """
        if first_name is not None and len(first_name) < 1:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UserUpdate.  # noqa: E501


        :return: The last_name of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UserUpdate.


        :param last_name: The last_name of this UserUpdate.  # noqa: E501
        :type: str
        """
        if last_name is not None and len(last_name) < 1:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._last_name = last_name

    @property
    def address(self):
        """Gets the address of this UserUpdate.  # noqa: E501


        :return: The address of this UserUpdate.  # noqa: E501
        :rtype: UserUpdateAddress
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this UserUpdate.


        :param address: The address of this UserUpdate.  # noqa: E501
        :type: UserUpdateAddress
        """

        self._address = address

    @property
    def email(self):
        """Gets the email of this UserUpdate.  # noqa: E501


        :return: The email of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserUpdate.


        :param email: The email of this UserUpdate.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def phone(self):
        """Gets the phone of this UserUpdate.  # noqa: E501


        :return: The phone of this UserUpdate.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this UserUpdate.


        :param phone: The phone of this UserUpdate.  # noqa: E501
        :type: str
        """
        if phone is not None and len(phone) < 1:
            raise ValueError("Invalid value for `phone`, length must be greater than or equal to `1`")  # noqa: E501

        self._phone = phone

    @property
    def pending_address_changes(self):
        """Gets the pending_address_changes of this UserUpdate.  # noqa: E501


        :return: The pending_address_changes of this UserUpdate.  # noqa: E501
        :rtype: list[object]
        """
        return self._pending_address_changes

    @pending_address_changes.setter
    def pending_address_changes(self, pending_address_changes):
        """Sets the pending_address_changes of this UserUpdate.


        :param pending_address_changes: The pending_address_changes of this UserUpdate.  # noqa: E501
        :type: list[object]
        """

        self._pending_address_changes = pending_address_changes

    @property
    def update_cusno(self):
        """Gets the update_cusno of this UserUpdate.  # noqa: E501


        :return: The update_cusno of this UserUpdate.  # noqa: E501
        :rtype: int
        """
        return self._update_cusno

    @update_cusno.setter
    def update_cusno(self, update_cusno):
        """Sets the update_cusno of this UserUpdate.


        :param update_cusno: The update_cusno of this UserUpdate.  # noqa: E501
        :type: int
        """
        if update_cusno is not None and update_cusno > 9223372036854775807:  # noqa: E501
            raise ValueError("Invalid value for `update_cusno`, must be a value less than or equal to `9223372036854775807`")  # noqa: E501
        if update_cusno is not None and update_cusno < -9223372036854775808:  # noqa: E501
            raise ValueError("Invalid value for `update_cusno`, must be a value greater than or equal to `-9223372036854775808`")  # noqa: E501

        self._update_cusno = update_cusno

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
